data_source retail:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/gcp/service_acc.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: 'source-datasets'
    dataset: retail
soda_cloud:
  host: cloud.soda.io
  api_key_id: "your soda instance api key id"
  api_key_secret: your soda api key secret